# Generated by Django 3.0.10 on 2020-12-10 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0004_auto_20201210_1010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slot',
            old_name='is_assigned',
            new_name='is_mentor_assigned',
        ),
        migrations.AddField(
            model_name='slot',
            name='assigned_students',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='slot',
            name='is_student_assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slot',
            name='max_students',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='slot',
            name='computer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='program.Computer'),
        ),
    ]
