# Generated by Django 3.0.10 on 2020-12-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0005_auto_20201210_1027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slot',
            old_name='end',
            new_name='schedule_end',
        ),
        migrations.RenameField(
            model_name='slot',
            old_name='start',
            new_name='schedule_start',
        ),
        migrations.AddField(
            model_name='slot',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slot',
            name='start_date',
            field=models.DateField(auto_now=True),
        ),
    ]
