# Generated by Django 3.0.10 on 2020-11-15 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='UserType',
            field=models.IntegerField(choices=[('0', 'MENTOR')], default='0'),
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=254, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=254, null=True, verbose_name='Last Name')),
                ('personal_email', models.EmailField(max_length=254, null=True, unique=True, verbose_name='Personal Email')),
                ('vbb_email', models.EmailField(max_length=254, null=True, unique=True, verbose_name='Assigned VBB Email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Phone Number')),
                ('adult', models.CharField(max_length=3, null=True)),
                ('occupation', models.CharField(blank=True, max_length=70, null=True, verbose_name='Occupation')),
                ('vbb_chapter', models.CharField(blank=True, max_length=40, null=True, verbose_name='VBB Chapter')),
                ('affiliation', models.CharField(blank=True, max_length=70, null=True, verbose_name='Affiliation')),
                ('referral_source', models.CharField(blank=True, max_length=200, null=True, verbose_name='Refferal')),
                ('languages', models.CharField(blank=True, max_length=70, null=True)),
                ('time_zone', models.CharField(max_length=40, null=True)),
                ('charged', models.TextField(max_length=1024, null=True)),
                ('initials', models.CharField(max_length=6, null=True)),
                ('desired_involvement', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=70, null=True)),
                ('advisor_notes', models.TextField(blank=True, max_length=512, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mp', to=settings.AUTH_USER_MODEL, verbose_name='User Object of Mentor')),
            ],
        ),
    ]
