# Generated by Django 3.0.10 on 2020-11-15 15:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_auto_20201115_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Mentor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('notes', models.TextField(blank=True, default=None, null=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('is_mentor_confirmed', models.BooleanField(default=None)),
                ('is_mentee_confirmed', models.BooleanField(default=None)),
                ('derived_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='session.SessionRule')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
